In [113]:
import numpy as np
import cv2 as cv

In [185]:
print(cv.__version__)

4.2.0


In [186]:
img = cv.imread('data/frame100-(41.8, 62.7, 25.9).png')
img2 = cv.imread('data/frame15-(7.0, 7.0, 0.4).png')

In [188]:
def show_img_list(img_list):
    for i in range(len(img_list)):
        cv.imshow(str(i), img_list[i])
    cv.waitKey(0)
    cv.destroyAllWindows()

In [190]:
def apply_filter(img):
    lower = np.array([110,50, 50])
    upper = np.array([130,255,255])
    hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)
    mask = cv.inRange(hsv, lower, upper)
    return cv.bitwise_and(img, img, mask= mask)

In [195]:
show_img_list([apply_filter(img), apply_filter(img2)])

In [ ]:
cv.inrange()

In [170]:
show_img_list([apply_filter(img2)])

In [63]:
img = cv.medianBlur(img, 5)
cimg = cv.cvtColor(img, cv.COLOR_GRAY2BGR)

In [64]:
circles = cv.HoughCircles(img,cv.HOUGH_GRADIENT,1,20,
                            param1=50,param2=30,minRadius=0,maxRadius=0)

In [65]:
circles = np.uint16(np.around(circles))
for i in circles[0,:]:
    # draw the outer circle
    cv.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
    # draw the center of the circle

In [97]:
show_img_list([cimg, img])

KeyboardInterrupt: 

In [68]:
print(circles)

[[[414 506  56]
  [214 360 166]
  [414 426 142]
  [388 446 111]
  [220 416  82]
  [418 528  13]]]


In [82]:
red = np.uint8([[[0,0,255 ]]])
blue = np.uint8([[[255,0,0 ]]])
print(cv.cvtColor(red,cv.COLOR_BGR2HSV))
print(cv.cvtColor(blue,cv.COLOR_BGR2HSV))

[[[  0 255 255]]]
[[[120 255 255]]]


In [87]:
hsv_test = np.uint8([[[  1, 203, 201]]])
show_img_list([red, blue, cv.cvtColor( hsv_test, cv.COLOR_HSV2BGR)])